// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // The CLI (migrate/db push/db seed) needs a direct, non-pooled connection —
  // Supabase's pgbouncer transaction-mode pooler (DATABASE_URL) doesn't support
  // the session-level advisory locks Prisma Migrate relies on. The app's own
  // runtime connection (src/server/db.ts, via the pg driver adapter) uses the
  // pooled DATABASE_URL instead, since serverless functions need pooling.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
