-- Customer profile fields: salutation and date of birth.
--
-- Hand-written rather than generated by `prisma migrate dev`, which cannot run
-- on this project — it would drop the generated "searchVector" column. See the
-- note on Product.searchVector in schema.prisma.

-- The probe run of `migrate dev` may have already created this type before
-- failing, so guard it.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Title') THEN
    CREATE TYPE "Title" AS ENUM ('mr', 'mrs', 'ms');
  END IF;
END
$$;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "title" "Title";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dateOfBirth" DATE;
