-- Category.icon: a Lucide icon name (or emoji) shown beside the label in the
-- header's category nav.
--
-- Hand-written rather than generated by `prisma migrate dev`, which cannot run
-- on this project — it would drop the generated "searchVector" column. See the
-- note on Product.searchVector in schema.prisma.

-- Nullable with no default: existing categories keep rendering as label-only
-- until someone sets an icon in /admin/categories, so this is safe to apply
-- against a live database with no backfill.
ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "icon" TEXT;
